### PR TITLE
Adding functionality to Flashforge Adventure 5M wifi serial connection

### PR DESCRIPTION
**Pull request by iherbak**
Dear Flashforge,

I made an implementation of the serial tcp connection using some rev engineering using Wireshark. Sorry but I was impatient this time.

It is working on my Adventurer 5M pro.

However 
- some error handling might be added (e.g. the printer is busy etc)
- I don't know all the available spec commands that might be included
- C++ not my primary language so the code might be not the cleanest

Please revise and adapt my code and make it available to the community as we are eagerly waiting for this to happen.

Thank you,
A0vy

### CODE REVIEW

**Comment by francisconroy** [comment]
Thanks for the awesome work, I'm a software engineer in Australia with a background in C/CPP so might be able to give you some assistance with this. Just bought an FF adventurer 5M a few weeks back and can't wait to start using this!

**Comment by AJolly** [comment]
Love this.  Btw, you've probably already seen it, but  klipper on the 5m - https://github.com/g992/flashforge-ad5m-5mpro-research/issues/6

**Comment by EVSDELAT** [comment]
I'm a newbie, and I'd like to ask how to add your program to ORCA so that the Adventure 5M has WIFI remote printing function

**Comment by iherbak** [comment]
@EVSDELAT Find my fork. There is already a windows release.

**Comment by FlashforgeOfficial** [comment]
Hi, @iherbak  seems that there exist some fails in the check profile part in merging. Could you re-check on related part?

image

**Comment by FlashforgeOfficial** [comment]
> @FlashforgeOfficial The check_profiles workflow runs on pull request merge, however it is configured to download the latest profiles from https://github.com/SoftFever/OrcaSlicer/releases/download/nightly-builds/orca_custom_preset_tests.zip. And mine does not contains all the latest files. Either disable the workflow or change the check profiles.yml in your repo to point to the correct release url. Or first merge SoftEver main into your main then i could create another pull request to your main from mine

Cool @iherbak  . I am going to catch up with Softfever's main and do a PR for G3U profile first. I will let you know when it's ready for you to do a follow up PR for this thread.

**Comment by iherbak** [comment]
@FlashforgeOfficial would it be possible to get more insides about the other printers communication details for me? E.g. Guider so i could extend the support? I think it would be beneficial for the community.
Thanks

**Comment by FlashforgeOfficial** [comment]
> @FlashforgeOfficial would it be possible to get more insides about the other printers communication details for me? E.g. Guider so i could extend the support? I think it would be beneficial for the community. Thanks

 Below is a remote connection for Guider3 Ultra with FlashPrint.
https://wiki.flashforge.com/en/guider_series/manual/print-via-flashprint-5

Based on what I know, the way they connect to Flashprint is similar.

**Pull request merged**
